name: Update Blog Posts

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 매일 자정에 실행

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set time zone
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
          echo "Asia/Seoul" | sudo tee /etc/timezone
          date

      - name: Push changes
        run: |
          git config --global user.name 'hjoo830'
          git config --global user.email 'hjoo830@naver.com'
          git pull origin main --rebase
          git push https://${{ secrets.GH_PAT }}@github.com/hjoo830/velog.git

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install feedparser gitpython

      - name: Run script
        run: python scripts/update_blog.py
